# POST http://localhost:4000/api/auth/resetmatkhau HTTP/1.1
POST http://203.205.6.12:4000/api/auth/resetmatkhau HTTP/1.1
content-type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZvIjp7ImlkIjoibDE2MVJFbnE2U2hQcUdBRmpzZEgiLCJlbWFpbCI6Imtha2FrZWtlMzEyQGdtYWlsLmNvbSIsIm5hbWUiOiJOZ2hpYSBWbyIsInBhc3N3b3JkIjoiJDJiJDEwJFhDSG1pejRyMS9iRGtqUmtZQkFXLi5USjhZVnFMQjh3ODA0c3hYRXNQczN6bUVpNk92d2NpIiwiYWRkcmVzcyI6ImFiYyBhIHN0cmVldCIsIndvcmtwbGFjZSI6IlPhu58gR1RWVCIsInBob25lTnVtYmVyIjoiMDkwNTg4NjEzMSIsInRva2VuIjoiYXpoREtoOUVGakp6TGc2ZVNGSWNNcUlKdkFZZ2ZHQWMzR1BWUUxXUCJ9LCJpYXQiOjE2NDc0MjI4MzUsImV4cCI6MTY0NzQyNDYzNX0.SYV-O-6KA4DM8qDjJwCzVsdcVqmzDWr48U_lUy8C_O8",
	"newPassword": "abc123"
}