version: '3'

services:
  # Database
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - /home/tindh/monitoring_db:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty123@
      MYSQL_DATABASE: quantracdb2
      MYSQL_USER: root
      MYSQL_PASSWORD: Qwerty123@
    networks:
      - monitoring_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Qwerty123@ 
    networks:
      - monitoring_network
networks:
  monitoring_network: