USE 'quantracdb'
GO
INSERT INTO permissions (id, name, displayName) VALUES ('11qPomXM73PWqYKXzYwk', 'edit_data', 'Chỉnh sửa dữ liệu');
INSERT INTO permissions (id, name, displayName) VALUES ('12qPomXM73PWqYKXzYwk', 'delete_data', 'Xóa dữ liệu');
INSERT INTO permissions (id, name, displayName) VALUES ('13qPomXM73PWqYKXzYwk', 'insert_data', 'Thêm dữ liệu');
INSERT INTO permissions (id, name, displayName) VALUES ('14qPomXM73PWqYKXzYwk', 'view_station_config', 'Xem thông tin trạm');
INSERT INTO permissions (id, name, displayName) VALUES ('15qPomXM73PWqYKXzYwk', 'edit_station_config', 'Sửa thông tin trạm');
INSERT INTO permissions (id, name, displayName) VALUES ('16qPomXM73PWqYKXzYwk', 'insert_station', 'Thêm mới trạm');
INSERT INTO permissions (id, name, displayName) VALUES ('17qPomXM73PWqYKXzYwk', 'delete_station', 'Xóa trạm');
INSERT INTO permissions (id, name, displayName) VALUES ('18qPomXM73PWqYKXzYwk', 'view_camera_info', 'Xem thông tin camera');
INSERT INTO permissions (id, name, displayName) VALUES ('19qPomXM73PWqYKXzYwk', 'edit_camera_info', 'Sửa thông tin camera');
INSERT INTO permissions (id, name, displayName) VALUES ('20qPomXM73PWqYKXzYwk', 'insert_camera', 'Thêm mới camera');
INSERT INTO permissions (id, name, displayName) VALUES ('21qPomXM73PWqYKXzYwk', 'delete_camera', 'Xóa camera');
INSERT INTO permissions (id, name, displayName) VALUES ('22qPomXM73PWqYKXzYwk', 'view_stream_camera', 'Xem camera trực tuyến');
INSERT INTO permissions (id, name, displayName) VALUES ('23qPomXM73PWqYKXzYwk', 'sample_control', 'Điều khiển lấy mẫu');
INSERT INTO permissions (id, name, displayName) VALUES ('24qPomXM73PWqYKXzYwk', 'check_station_location', 'Kiểm tra vị trí trạm quan trắc');
INSERT INTO permissions (id, name, displayName) VALUES ('25qPomXM73PWqYKXzYwk', 'view_monitoring_group', 'Xem thông tin nhóm quan trắc');
INSERT INTO permissions (id, name, displayName) VALUES ('26qPomXM73PWqYKXzYwk', 'edit_monitoring_group', 'Sửa thông tin nhóm quan trắc');
INSERT INTO permissions (id, name, displayName) VALUES ('27qPomXM73PWqYKXzYwk', 'insert_monitoring_group', 'Thêm thông tin nhóm quan trắc');
INSERT INTO permissions (id, name, displayName) VALUES ('28qPomXM73PWqYKXzYwk', 'delete_monitoring_group', 'Xóa nhóm quan trắc');
INSERT INTO permissions (id, name, displayName) VALUES ('29qPomXM73PWqYKXzYwk', 'view_indicator', 'Xem chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('30qPomXM73PWqYKXzYwk', 'edit_indicator', 'Sửa chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('31qPomXM73PWqYKXzYwk', 'insert_indicator', 'Thêm chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('32qPomXM73PWqYKXzYwk', 'delete_indicator', 'Xóa chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('33qPomXM73PWqYKXzYwk', 'view_indicator_threshold', 'Xem ngưỡng chí số');
INSERT INTO permissions (id, name, displayName) VALUES ('34qPomXM73PWqYKXzYwk', 'edit_indicator_threshold', 'Sửa ngưỡng chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('35qPomXM73PWqYKXzYwk', 'insert_indicator_threshold', 'Thêm ngưỡng chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('36qPomXM73PWqYKXzYwk', 'delete_indicator_threshold', 'Xóa ngưỡng chỉ số');
INSERT INTO permissions (id, name, displayName) VALUES ('37qPomXM73PWqYKXzYwk', 'view_user_group', 'Xem thông tin nhóm người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('38qPomXM73PWqYKXzYwk', 'edit_user_group', 'Sửa thông tin nhóm người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('39qPomXM73PWqYKXzYwk', 'insert_user_group', 'Thêm nhóm người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('40qPomXM73PWqYKXzYwk', 'delete_user_group', 'Xóa nhóm người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('41qPomXM73PWqYKXzYwk', 'view_user_info', 'Xem thông tin người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('42qPomXM73PWqYKXzYwk', 'edit_user_info', 'Sửa thông tin người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('43qPomXM73PWqYKXzYwk', 'insert_user', 'Thêm người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('44qPomXM73PWqYKXzYwk', 'delete_user', 'Xóa người dùng');
INSERT INTO permissions (id, name, displayName) VALUES ('45qPomXM73PWqYKXzYwk', 'view_general_report', 'Xem báo cáo tổng quát');
INSERT INTO permissions (id, name, displayName) VALUES ('46qPomXM73PWqYKXzYwk', 'view_specific_report', 'Xem báo cáo chi tiết');
INSERT INTO permissions (id, name, displayName) VALUES ('47qPomXM73PWqYKXzYwk', 'export_report', 'Export báo cáo');
INSERT INTO permissions (id, name, displayName) VALUES ('48qPomXM73PWqYKXzYwk', 'view_activity_diary', 'Xem nhật ký');
INSERT INTO permissions (id, name, displayName) VALUES ('49qPomXM73PWqYKXzYwk', 'delete_activity_diary', 'Xóa nhật ký');
INSERT INTO permissions (id, name, displayName) VALUES ('50qPomXM73PWqYKXzYwk', 'export_diary', 'Xuất nhật ký');
INSERT INTO permissions (id, name, displayName) VALUES ('52qPomXM73PWqYKXzYwk', 'view_system_config', 'Xem hệ thống');
INSERT INTO permissions (id, name, displayName) VALUES ('53qPomXM73PWqYKXzYwk', 'edit_system_config', 'Sửa dữ liệu hệ thống');
INSERT INTO permissions (id, name, displayName) VALUES ('54qPomXM73PWqYKXzYwk', 'upload_data', 'Nhập số liệu ');
INSERT INTO permissions (id, name, displayName) VALUES ('55qPomXM73PWqYKXzYwk', 'auto_update_station', 'Tự động cập nhật trạm mới');
