# POST http://203.205.6.12/api/tiepnhandulieu?format=json HTTP/1.1
POST http://localhost/api/tiepnhandulieu?format=json HTTP/1.1
content-type: application/json

{
  "time": "2022-03-25 16:27:15",
  "idStation": "Lm2CVayapVlTDYa9Tfwu",
  "apiKey": "9418796589e133a09ec7dd011a2ff3f8fc2e5a55",
  "Ungsuat1": "-147.271 MPa",
  "Ungsuat2": "-169.373 MPa",
  "Ungsuat3": "-168.06 MPa",
  "Ungsuat4": "-117.212 MPa",
  "Ungsuat5": "-99.771 MPa",
  "Ungsuat6": "-245.48 MPa",
  "Ungsuat7": "-237.319 MPa",
  "Ungsuat8": "-207.741 MPa",
  "Ungsuat9": "-183.751 MPa",
  "Ungsuat10": "-232.976 MPa",
  "Ungsuat11": "-195.834 MPa",
  "Ungsuat12": "-214.975 MPa",
  "Ungsuat13": "-212.393 MPa",
  "Ungsuat14": "-209.693 MPa",
  "Ungsuat15": "-204.786 MPa",
  "Ungsuat16": "-6.625 MPa",
  "Ungsuat17": "-10.861 MPa",
  "Ungsuat18": "-105.405 MPa",
  "Ungsuat19": "71.406 MPa",
  "Ungsuat20": "3.267 MPa",
  "Ungsuat21": "-2.517 MPa",
  "Ungsuat22": "-7.816 MPa",
  "Ungsuat23": "-46.633 MPa",
  "Ungsuat24": "4.336 MPa",
  "Ungsuat25": "2.958 MPa",
  "Ungsuat26": "-1.68 MPa",
  "Ungsuat27": "47.305 MPa",
  "Ungsuat28": "-93.986 MPa",
  "Ungsuat29": "-89.071 MPa",
  "Ungsuat30": "40.575 MPa",
  "Ungsuat31": "2.76 MPa",
  "Ungsuat32": "-7.895 MPa",
  "Ungsuat33": "72.198 MPa",
  "Ungsuat34": "-54.493 MPa",
  "Ungsuat35": "3.854 MPa",
  "Ungsuat36": "-12.63 MPa",
  "Ungsuat37": "39.421 MPa",
  "Ungsuat38": "-63.668 MPa",
  "Ungsuat39": "-96.766 MPa",
  "Ungsuat40": "40.575 MPa",
  "Ungsuat41": "4.243 MPa",
  "Ungsuat42": "-58.576 MPa",
  "Ungsuat43": "20.48 MPa",
  "Ungsuat44": "1.295 MPa",
  "Ungsuat45": "-5.717 MPa",
  "Ungsuat46": "43.268 MPa",
  "Ungsuat47": "-57.378 MPa",
  "Ungsuat48": "2.135 MPa",
  "Ungsuat49": "-1.374 MPa",
  "Ungsuat50": "0.992 MPa",
  "Ungsuat51": "-2.958 MPa",
  "Ungsuat52": "-1.311 MPa",
  "Ungsuat53": "-3.16 MPa",
  "Ungsuat54": "-7.905 MPa",
  "Ungsuat55": "-8.459 MPa",
  "Ungsuat56": "-6.447 MPa",
  "Ungsuat57": "-8.559 MPa",
  "Ungsuat58": "-8.358 MPa",
  "Ungsuat59": "-8.56 MPa",
  "Chuyenvi1": "0.381 mm",
  "Chuyenvi2": "0.426 mm",
  "Chuyenvi3": "0.429 mm",
  "Chuyenvi4": "0.25 mm",
  "Gocxoay1": "-0.007 °",
  "Gocxoay2": "0 °",
  "NhietdoKC1": "28.77 °C",
  "NhietdoKC2": "44.76 °C",
  "NhietdoKC3": "30.43 °C",
  "NhietdoKC4": "48.02 °C",
  "NhietdoKC5": "31.18 °C",
  "NhietdoKC6": "46.51 °C",
  "NhietdoKC7": "30.66 °C",
  "NhietdoKC8": "26.17 °C"
}