POST http://localhost:4000/api/tiepnhandulieu?format=json HTTP/1.1
content-type: application/json

{
	"time": "2022-01-15 11:30:00",
	"idStation": "qMJZtuzR6Ba7Z8leTbbj",
	"CO": "21050 mg/m3",
	"Nox": "54 ug/m3",
	"TSP": "245"
}