# POST http://203.205.6.12:4000/api/tiepnhandulieu?format=json HTTP/1.1
POST http://localhost:4000/api/tiepnhandulieu?format=json HTTP/1.1
content-type: application/json

{
	"time": "2022-02-28 08:12:15",
	"idStation": "eU3KgTHimnZtAqiFGTcq",
	"apiKey": "cff48a7e427d4b1515983c1d7ebd877ee4cbff66",
	"US1": "12.21 MPa",
	"US2": "7.72 MPa",
	"CV1": "9.97 M"
}