 IF OBJECT_ID('[notifications]', 'U') IS NOT NULL DROP TABLE [notifications];
 IF OBJECT_ID('[user_station]', 'U') IS NOT NULL DROP TABLE [user_station];
 IF OBJECT_ID('[user_management]', 'U') IS NOT NULL DROP TABLE [user_management];
 IF OBJECT_ID('[user_role]', 'U') IS NOT NULL DROP TABLE [user_role];
 IF OBJECT_ID('[user_access_tokens]', 'U') IS NOT NULL DROP TABLE [user_access_tokens];
 IF OBJECT_ID('[users]', 'U') IS NOT NULL DROP TABLE [users];
 IF OBJECT_ID('[station_indicators]', 'U') IS NOT NULL DROP TABLE [station_indicators];
 IF OBJECT_ID('[systems]', 'U') IS NOT NULL DROP TABLE [systems];
 IF OBJECT_ID('[station_groups]', 'U') IS NOT NULL DROP TABLE [station_groups];
 IF OBJECT_ID('[station_cameras]', 'U') IS NOT NULL DROP TABLE [station_cameras];
 IF OBJECT_ID('[sample_history]', 'U') IS NOT NULL DROP TABLE [sample_history];
 IF OBJECT_ID('[roles]', 'U') IS NOT NULL DROP TABLE [roles];
 IF OBJECT_ID('[monitoring_types]', 'U') IS NOT NULL DROP TABLE [monitoring_types];
 IF OBJECT_ID('[monitoring_data]', 'U') IS NOT NULL DROP TABLE [monitoring_data];
 IF OBJECT_ID('[monitoring_data_info]', 'U') IS NOT NULL DROP TABLE [monitoring_data_info];
 IF OBJECT_ID('[stations]', 'U') IS NOT NULL DROP TABLE [stations];
 IF OBJECT_ID('[indicator_threshold]', 'U') IS NOT NULL DROP TABLE [indicator_threshold];
 IF OBJECT_ID('[monitoring_groups]', 'U') IS NOT NULL DROP TABLE [monitoring_groups];
 IF OBJECT_ID('[indicators]', 'U') IS NOT NULL DROP TABLE [indicators];
 IF OBJECT_ID('[firmwares]', 'U') IS NOT NULL DROP TABLE [firmwares];
 IF OBJECT_ID('[alert_history]', 'U') IS NOT NULL DROP TABLE [alert_history];
 IF OBJECT_ID('[alert_history]', 'U') IS NOT NULL DROP TABLE [alert_history];
 IF OBJECT_ID('[alert_history]', 'U') IS NULL CREATE TABLE [alert_history] ([id] NVARCHAR(20) NOT NULL , [station_id] NVARCHAR(20) NOT NULL, [alert_type] TINYINT NOT NULL, [alert_at] DATETIMEOFFSET NOT NULL, [indicator] NVARCHAR(64) NULL, [value] FLOAT NULL, [unit] NVARCHAR(255) NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[alert_history]';
 IF OBJECT_ID('[firmwares]', 'U') IS NOT NULL DROP TABLE [firmwares];
 IF OBJECT_ID('[firmwares]', 'U') IS NULL CREATE TABLE [firmwares] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [version] NVARCHAR(50) NOT NULL, [firmware_data] DATETIMEOFFSET NOT NULL, [status] TINYINT NULL, [url] NVARCHAR(255) NOT NULL, [created_at] DATETIMEOFFSET NOT NULL, [updated_at] DATETIMEOFFSET NOT NULL, [deleted_at] DATETIMEOFFSET NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[firmwares]';
 IF OBJECT_ID('[indicators]', 'U') IS NOT NULL DROP TABLE [indicators];
 IF OBJECT_ID('[indicators]', 'U') IS NULL CREATE TABLE [indicators] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [monitoringType] NVARCHAR(255) NOT NULL, [symbol] NVARCHAR(255) NOT NULL, [unit] NVARCHAR(255) NULL, [description] NVARCHAR(MAX) NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[indicators]';
 IF OBJECT_ID('[monitoring_groups]', 'U') IS NOT NULL DROP TABLE [monitoring_groups];
 IF OBJECT_ID('[monitoring_groups]', 'U') IS NULL CREATE TABLE [monitoring_groups] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [monitoringType] NVARCHAR(20) NOT NULL, [symbol] NVARCHAR(255) NOT NULL, [description] NVARCHAR(MAX) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[monitoring_groups]';
 IF OBJECT_ID('[indicator_threshold]', 'U') IS NOT NULL DROP TABLE [indicator_threshold];
 IF OBJECT_ID('[indicator_threshold]', 'U') IS NULL CREATE TABLE [indicator_threshold] ([id] NVARCHAR(20) NOT NULL , [monitoringType] NVARCHAR(20) NOT NULL, [indicatorId] NVARCHAR(20) NOT NULL, [monitoringGroupId] NVARCHAR(20) NOT NULL, [upperLimit] NVARCHAR(20) NOT NULL, [lowerLimit] NVARCHAR(20) NOT NULL, [hourLimit] NVARCHAR(20) NULL, [safetyDescription] NVARCHAR(MAX) NULL, [overThresholdDescription] NVARCHAR(MAX) NULL, PRIMARY KEY ([id]), FOREIGN KEY ([indicatorId]) REFERENCES [indicators] ([id]) ON DELETE NO ACTION, FOREIGN KEY ([monitoringGroupId]) REFERENCES [monitoring_groups] ([id]) ON DELETE NO ACTION);
 EXEC sys.sp_helpindex @objname = N'[indicator_threshold]';
 IF OBJECT_ID('[stations]', 'U') IS NOT NULL DROP TABLE [stations];
 IF OBJECT_ID('[stations]', 'U') IS NULL CREATE TABLE [stations] ([id] NVARCHAR(20) NOT NULL , [monitoringType] NVARCHAR(255) NOT NULL, [name] NVARCHAR(255) NOT NULL, [monitoringGroupId] NVARCHAR(20) NOT NULL, [symbol] NVARCHAR(255) NOT NULL, [address] NVARCHAR(255) NOT NULL, [phone] NVARCHAR(20) NOT NULL, [image] NVARCHAR(100) NOT NULL, [rootLocation] NVARCHAR(255) NULL, [lastedLocation] NVARCHAR(255) NULL, [updateLocationStatus] TINYINT NOT NULL, [installedAt] DATETIMEOFFSET NULL, [verifiedAt] DATETIMEOFFSET NULL, [verificationOrganization] NVARCHAR(255) NULL, [emittedFrequency] INTEGER NULL, [ftpFolder] NVARCHAR(255) NULL, [ftpFilename] NVARCHAR(255) NULL, [latestSentAt] DATETIMEOFFSET NULL, [sendftpStatus] TINYINT NULL, [receiveftpStatus] TINYINT NULL, [lastedIndicatorOverThreshold] NVARCHAR(20) NULL, [numberOfThreshold] INTEGER NULL, [numberOfAlertThreshold] INTEGER NULL, [alertThresholdStatus] TINYINT NULL, [numberOfAlertStructure] INTEGER NULL, [alertStructureStatus] TINYINT NULL, [numberOfDisconnection] INTEGER NULL, [alertDisconnectionStatus] TINYINT NULL, [battery] INTEGER NULL, [activityStatus] TINYINT NULL, [publicStatus] TINYINT NULL, [createdAt] DATETIMEOFFSET NULL, [updatedAt] DATETIMEOFFSET NULL, [deletedAt] DATETIMEOFFSET NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[stations]';
 IF OBJECT_ID('[monitoring_data_info]', 'U') IS NOT NULL DROP TABLE [monitoring_data_info];
 IF OBJECT_ID('[monitoring_data_info]', 'U') IS NULL CREATE TABLE [monitoring_data_info] ([id] NVARCHAR(20) NOT NULL , [stationId] NVARCHAR(20) NOT NULL, [location] NVARCHAR(60) NULL, [battery] NVARCHAR(255) NULL, [monitoringContent] NVARCHAR(1024) NOT NULL, [sentAt] DATETIMEOFFSET NOT NULL, [isFtpdata] TINYINT NULL, [createdAt] DATETIMEOFFSET NULL, [updatedAt] DATETIMEOFFSET NULL, [deletedAt] DATETIMEOFFSET NULL, PRIMARY KEY ([id]), FOREIGN KEY ([stationId]) REFERENCES [stations] ([id]) ON DELETE NO ACTION);
 EXEC sys.sp_helpindex @objname = N'[monitoring_data_info]';
 IF OBJECT_ID('[monitoring_data]', 'U') IS NOT NULL DROP TABLE [monitoring_data];
 IF OBJECT_ID('[monitoring_data]', 'U') IS NULL CREATE TABLE [monitoring_data] ([id] NVARCHAR(20) NOT NULL , [idData] NVARCHAR(20) NOT NULL, [indicator] NVARCHAR(20) NOT NULL, [value] FLOAT NOT NULL, [unit] NVARCHAR(255) NOT NULL, [sensorStatus] NVARCHAR(2) NOT NULL, [createdAt] DATETIMEOFFSET NULL, [updatedAt] DATETIMEOFFSET NULL, [deletedAt] DATETIMEOFFSET NULL, PRIMARY KEY ([id]), FOREIGN KEY ([idData]) REFERENCES [monitoring_data_info] ([id]) ON DELETE CASCADE);
 EXEC sys.sp_helpindex @objname = N'[monitoring_data]';
 IF OBJECT_ID('[monitoring_types]', 'U') IS NOT NULL DROP TABLE [monitoring_types];
 IF OBJECT_ID('[monitoring_types]', 'U') IS NULL CREATE TABLE [monitoring_types] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [symbol] NVARCHAR(255) NOT NULL, [description] NVARCHAR(MAX) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[monitoring_types]';
 IF OBJECT_ID('[roles]', 'U') IS NOT NULL DROP TABLE [roles];
 IF OBJECT_ID('[roles]', 'U') IS NULL CREATE TABLE [roles] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [displayName] NVARCHAR(255) NULL, [permissions] NVARCHAR(MAX) NULL, [priority] SMALLINT NULL, [description] NVARCHAR(MAX) NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[roles]';
 IF OBJECT_ID('[sample_history]', 'U') IS NOT NULL DROP TABLE [sample_history];
 IF OBJECT_ID('[sample_history]', 'U') IS NULL CREATE TABLE [sample_history] ([id] NVARCHAR(20) NOT NULL , [station_id] NVARCHAR(20) NOT NULL, [sample_at] DATETIMEOFFSET NOT NULL, [user_id] NVARCHAR(20) NOT NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[sample_history]';
 IF OBJECT_ID('[station_cameras]', 'U') IS NOT NULL DROP TABLE [station_cameras];
 IF OBJECT_ID('[station_cameras]', 'U') IS NULL CREATE TABLE [station_cameras] ([id] NVARCHAR(20) NOT NULL , [stationId] NVARCHAR(20) NOT NULL, [name] NVARCHAR(255) NOT NULL, [host] NVARCHAR(255) NOT NULL, [port] NVARCHAR(255) NOT NULL, [camUser] NVARCHAR(255) NOT NULL, [camPass] NVARCHAR(255) NOT NULL, [rtspLink] NVARCHAR(MAX) NOT NULL, [details] NVARCHAR(MAX) NULL, [mode] NVARCHAR(255) NOT NULL, [deletedAt] DATETIMEOFFSET NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([stationId]) REFERENCES [stations] ([id]) ON DELETE NO ACTION);
 EXEC sys.sp_helpindex @objname = N'[station_cameras]';
 IF OBJECT_ID('[station_groups]', 'U') IS NOT NULL DROP TABLE [station_groups];
 IF OBJECT_ID('[station_groups]', 'U') IS NULL CREATE TABLE [station_groups] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [symbol] NVARCHAR(255) NOT NULL, [description] NVARCHAR(MAX) NULL, [created_at] DATETIMEOFFSET NOT NULL, [updated_at] DATETIMEOFFSET NOT NULL, [deleted_at] DATETIMEOFFSET NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[station_groups]';
 IF OBJECT_ID('[systems]', 'U') IS NOT NULL DROP TABLE [systems];
 IF OBJECT_ID('[systems]', 'U') IS NULL CREATE TABLE [systems] ([id] NVARCHAR(20) NOT NULL , [idSystem] NVARCHAR(20) NOT NULL, [name] NVARCHAR(255) NOT NULL, [value] NVARCHAR(MAX) NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[systems]';
 IF OBJECT_ID('[station_indicators]', 'U') IS NOT NULL DROP TABLE [station_indicators];
 IF OBJECT_ID('[station_indicators]', 'U') IS NULL CREATE TABLE [station_indicators] ([id] NVARCHAR(20) NOT NULL , [idStation] NVARCHAR(20) NOT NULL, [idIndicator] NVARCHAR(20) NOT NULL, [status] NVARCHAR(20) NOT NULL, [deletedAt] DATETIMEOFFSET NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([idStation]) REFERENCES [stations] ([id]) ON DELETE CASCADE, FOREIGN KEY ([idIndicator]) REFERENCES [indicators] ([id]) ON DELETE CASCADE);
 EXEC sys.sp_helpindex @objname = N'[station_indicators]';
 IF OBJECT_ID('[users]', 'U') IS NOT NULL DROP TABLE [users];
 IF OBJECT_ID('[users]', 'U') IS NULL CREATE TABLE [users] ([id] NVARCHAR(20) NOT NULL , [name] NVARCHAR(255) NOT NULL, [email] NVARCHAR(255) NOT NULL, [password] NVARCHAR(255) NOT NULL, [emailVerifiedAt] DATETIMEOFFSET NULL, [alertEmail] NVARCHAR(255) DEFAULT NULL, [phoneNumber] NVARCHAR(15) NOT NULL, [workplace] NVARCHAR(255) NOT NULL, [address] NVARCHAR(255) NOT NULL, [isActive] BIT NOT NULL, [deletedAt] NVARCHAR(255) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]));
 EXEC sys.sp_helpindex @objname = N'[users]';
 IF OBJECT_ID('[user_access_tokens]', 'U') IS NOT NULL DROP TABLE [user_access_tokens];
 IF OBJECT_ID('[user_access_tokens]', 'U') IS NULL CREATE TABLE [user_access_tokens] ([token] NVARCHAR(255) NOT NULL , [userId] NVARCHAR(20) NOT NULL, [description] NVARCHAR(MAX) 
NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([token]), FOREIGN KEY ([userId]) REFERENCES [users] ([id]) ON DELETE CASCADE);
 EXEC sys.sp_helpindex @objname = N'[user_access_tokens]';
 IF OBJECT_ID('[user_role]', 'U') IS NOT NULL DROP TABLE [user_role];
 IF OBJECT_ID('[user_role]', 'U') IS NULL CREATE TABLE [user_role] ([id] NVARCHAR(20) NOT NULL , [userId] NVARCHAR(20) NOT NULL, [roleId] NVARCHAR(20) NOT NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([userId]) REFERENCES [users] ([id]) ON DELETE CASCADE, FOREIGN KEY ([roleId]) REFERENCES [roles] ([id]) ON DELETE CASCADE);
 EXEC sys.sp_helpindex @objname = N'[user_role]';
 IF OBJECT_ID('[user_management]', 'U') IS NOT NULL DROP TABLE [user_management];
 IF OBJECT_ID('[user_management]', 'U') IS NULL CREATE TABLE [user_management] ([id] NVARCHAR(20) NOT NULL , [managerId] NVARCHAR(20) NOT NULL, [userId] NVARCHAR(20) NOT NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([managerId]) REFERENCES [users] ([id]) ON DELETE CASCADE, FOREIGN KEY ([userId]) REFERENCES [users] ([id]));
 EXEC sys.sp_helpindex @objname = N'[user_management]';
 IF OBJECT_ID('[user_station]', 'U') IS NOT NULL DROP TABLE [user_station];
 IF OBJECT_ID('[user_station]', 'U') IS NULL CREATE TABLE [user_station] ([id] NVARCHAR(20) NOT NULL , [userId] NVARCHAR(20) NOT NULL, [stationId] NVARCHAR(20) NOT NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([userId]) REFERENCES [users] ([id]) ON DELETE CASCADE, FOREIGN KEY ([stationId]) REFERENCES [stations] ([id]) ON DELETE NO ACTION);
 EXEC sys.sp_helpindex @objname = N'[user_station]';
 IF OBJECT_ID('[notifications]', 'U') IS NOT NULL DROP TABLE [notifications];
 IF OBJECT_ID('[notifications]', 'U') IS NULL CREATE TABLE [notifications] ([id] NVARCHAR(20) NOT NULL , [type] NVARCHAR(255) NULL, [stationId] NVARCHAR(20) NULL, [content] NVARCHAR(MAX) NULL, [createdAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([stationId]) REFERENCES [stations] ([id]) ON DELETE NO ACTION);
 EXEC sys.sp_helpindex @objname = N'[notifications]';
 IF OBJECT_ID('[user_notifications]', 'U') IS NOT NULL DROP TABLE [user_notifications];
 IF OBJECT_ID('[user_notifications]', 'U') IS NULL CREATE TABLE [user_notifications] ([id] NVARCHAR(20) NOT NULL , [receiverId] NVARCHAR(20) NOT NULL, [notificationId] NVARCHAR(20) NOT NULL, [isRead] BIT DEFAULT 0, [createdAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]), FOREIGN KEY ([receiverId]) REFERENCES [users] ([id]) ON DELETE NO ACTION, FOREIGN KEY ([notificationId]) REFERENCES [notifications] ([id]) ON DELETE CASCADE);
 EXEC sys.sp_helpindex @objname = N'[user_notifications]';