export const EventTypes = {
  INDICATOR_OVER_THRESHOLD: 'INDICATOR_OVER_THRESHOLD',
  FTP_FILE_STRUCTURE_WRONG: "FTP_FILE_STRUCTURE_WRONG",
  STATION_DISCONNECT: "STATION_DISCONNECT",
} 

export const MAXIMUM_FIREBASE_TOKENS = 1000