# POST http://sogtvt.monisoft.vn/api/quanlyapi/eYalbMK7hA9LuufWeLcK HTTP/1.1

# POST http://localhost:4000/api/quanlyapi/eYalbMK7hA9LuufWeLcK HTTP/1.1
# POST http://sogtvt.monisoft.vn/api/quanlyapi/eYalbMK7hA9LuufWeLcK HTTP/1.1
# content-type: application/json

# {
# 	"name": "Cộng Hòa Reception API",
# 	"description": "API nhận dữ liệu cho trạm Cộng Hòa",
# 	"type": "DATA_RECEPTION",
# 	"stationId": "0SyZXkuztHo42wLwBKNu"
# }

# POST http://localhost:4000/api/quanlyapi/eYalbMK7hA9LuufWeLcK HTTP/1.1
POST http://sogtvt.monisoft.vn/api/quanlyapi/eYalbMK7hA9LuufWeLcK HTTP/1.1
content-type: application/json

{
	"name": "Lê Minh Xuân Reception API",
	"description": "API nhận dữ liệu cho trạm Lê Minh Xuân",
	"type": "DATA_RECEPTION",
	"stationId": "aSRuDNCG3BiubH3Zyi4d"
}