@host = localhost
@port = 80 
@accessToke = TqQ3yzYOQ4f4t1a5GJudlSilBa8bZeGAG2Owkjtz


### Get latest data
POST http://{{host}}:{{port}}/api/dulieumoinhat/yKt2BKInvG6i9UisBoYV HTTP/1.1
Authorization: accessToken {{accessToke}};
Content-Type: application/json

{ 
  "stationId" : ["ALL", "Lm2CVayapVlTDYa9Tfwu", "YxU202EHVekg2EigKgYk", "VTwYfr9AxlIBzRabo6MU"] 
}